### ISSUE TITLE
May I ask why your core code Multi-periodic Decoupling Block is not reflected in the PDF?

### ISSUE THREAD

**Issue by fan196** [Hank0626/PDF#1]

**Comment by Hank0626** [comment]
Thank you for reaching out with your query. The core code for the Multi-periodic Decoupling Block is indeed an integral part of our framework, PDF. It can be found within our repository at:
https://github.com/Hank0626/PDF/blob/fd53cbc1795acd19cf2c2256095d12c5508b657d/layers/PDF_backbone.py#L45-L55


The operation of this block is designed to be straightforward, which is why we did not encapsulate it within a separate class. Our goal was to maintain simplicity and transparency in the implementation to facilitate ease of understanding and modification.

**Comment by Respectzz** [comment]
不是要做傅里叶变换吗  请问在哪里做的

**Comment by Hank0626** [comment]
> 不是要做傅里叶变换吗 请问在哪里做的

See #5

**Comment by Respectzz** [comment]
谢谢

**Comment by Respectzz** [comment]
所以在代码里没有体现出来吗

**Comment by Hank0626** [comment]
> 所以在代码里没有体现出来吗

嗯，提前对整个数据集做了FFT，然后当作先验超参输入
